export const BASE_TASK_COLUMNS = [
  { key: "inClass", label: "In-class", type: "number" as const, width: 90 },
  { key: "inClassAtls", label: "In-class ATLS", type: "number" as const, width: 110 },
  { key: "demo", label: "Demo", type: "number" as const, width: 80 },
  { key: "tutoring", label: "Tutoring", type: "number" as const, width: 90 },
  { key: "waitingClass", label: "Waiting class", type: "number" as const, width: 110 },
  { key: "clubActivity", label: "Club activity", type: "number" as const, width: 110 },
  { key: "parentMeeting", label: "Parent meeting", type: "number" as const, width: 120 },
  { key: "pickUpDropOff", label: "Pick up/ Drop off", type: "number" as const, width: 140 },
  {
    key: "pickUpDropOffAtls",
    label: "Pick up/ Drop off ATLS",
    type: "number" as const,
    width: 170,
  },
  { key: "sms", label: "SMS", type: "number" as const, width: 80 },
  { key: "smsAtls", label: "SMS ATLS", type: "number" as const, width: 100 },
  {
    key: "progressReport",
    label: "Progress/Gradebook Report",
    type: "number" as const,
    width: 200,
  },
  {
    key: "progressReportAtls",
    label: "Gradebook Report ATLS",
    type: "number" as const,
    width: 200,
    headerSpanClassName: "leading-[19px] text-[14px] font-bold",
  },
  {
    key: "prepareLessonTutoring",
    label: "Prepare lesson - Tutoring",
    type: "number" as const,
    width: 190,
  },
  {
    key: "meetingTraining",
    label: "Meeting/ Training",
    type: "number" as const,
    width: 150,
  },
  { key: "pt", label: "PT", type: "number" as const, width: 80 },
  { key: "discoveryCamp", label: "Discovery Camp", type: "number" as const, width: 130 },
  { key: "outing", label: "Outing", type: "number" as const, width: 90 },
  { key: "summer", label: "Summer", type: "number" as const, width: 90 },
  {
    key: "summerInstructors",
    label: "Summer Instructors",
    type: "number" as const,
    width: 150,
    headerSpanClassName: "text-[11.2px] font-bold leading-[16.8px]",
  },
  {
    key: "prepareLessonClubs",
    label: "Prepare lesson - Clubs",
    type: "number" as const,
    width: 170,
  },
  { key: "conductTest", label: "Conduct test", type: "number" as const, width: 110 },
  {
    key: "renewalProjects",
    label: "Renewal Projects",
    type: "number" as const,
    width: 140,
  },
  { key: "supportLxo", label: "Support LXO", type: "number" as const, width: 110 },
  { key: "supportEc", label: "Support EC", type: "number" as const, width: 100 },
  { key: "supportMkt", label: "Support MKT", type: "number" as const, width: 110 },
  { key: "lpar01", label: "LPAR01", type: "number" as const, width: 90 },
  { key: "lret01", label: "LRET01", type: "number" as const, width: 90 },
  { key: "ldem01", label: "LDEM01", type: "number" as const, width: 90 },
  { key: "ldec01", label: "LDEC01", type: "number" as const, width: 90 },
  { key: "moth01", label: "MOTH01", type: "number" as const, width: 90 },
  { key: "totalHours", label: "Total Hours", type: "number" as const, width: 110, cellClassName: "font-black text-slate-900 bg-slate-50" },
  { key: "academicHours", label: "Academic Hours", type: "number" as const, width: 130, cellClassName: "font-bold text-rose-600 bg-rose-50/20" },
  {
    key: "adminHours",
    label: "Admin Hours",
    type: "number" as const,
    width: 110,
    cellClassName: "font-bold text-emerald-600 bg-emerald-50/20",
    headerSpanClassName: "text-xs no-underline leading-[11px] text-[#49780f]",
  },
];
